### ISSUE TITLE
Uncaught TypeError: existing is undefined

### ISSUE THREAD

**Issue by vitormaduro** [CarlosFdez/world-explorer#1]
Running Foundry 0.8.9 on Firefox, and after activating the module in a scene and selecting the menu option to toggle the tiles, the console gets full of errors when moving the mouse. The problem seems to be in this function:

    isRevealed(x, y) {
        const position = canvas.grid.getCenter(x, y).map(Math.round);
        const existing = this.scene.getFlag(MODULE, "revealed");
        const key = makePositionKey(position);
        return existing.some((existing) => makePositionKey(existing) === key);
    }

**Comment by CarlosFdez** [comment]
Easy enough fix, thanks for reporting

**Comment by CarlosFdez** [comment]
Should be good now. Surprised it wasn't caught during the retest at all.
