### ISSUE TITLE
Option to reset fog

### ISSUE THREAD

**Issue by epsilon7430** [CarlosFdez/world-explorer#10]
As a GM user, I would like to be able to reset the complete fog coverage with a single mouse click instead of having to toggle individual tiles.

(World Explorer appears to be the only module, suitable for hex crawls and masking areas, that functions in Foundry v9.  I really appreciate that it is available and being actively maintained.  Thank you!)

**Comment by CarlosFdez** [comment]
No problem! 

I'll likely do this soon once I find some time. It won't take very long for this feature at all.

**Comment by CarlosFdez** [comment]
This exists now in version 0.3. If there's any issues with it please let me know.

Its not a single mouse click though, its two via dialog, but hopefully that's not too much worse.

**Comment by epsilon7430** [comment]
Just upgraded to v9 and confirmed that this enhancement works great.  The warning dialog helps avoid accidents. Thank you!

**Comment by YenBenGrey** [comment]
How do you do this? I am in v11
