### ISSUE TITLE
Mouse click drag does not work using Toggle tool

### ISSUE THREAD

**Issue by epsilon7430** [CarlosFdez/world-explorer#12]
I'm not sure if the toggle tool is meant to support click-drag operation?  If yes, it doesn't work in my case - both in Foundry versions 0.8.9 and 9.238 - no console errors.

In v9, this console warning appears when I begin to drag the mouse with the button clicked:

Deprecated since V9 and will be removed in V10. Use game.keyboard.isModifierActive(KeyboardManager.MODIFIER_KEYS.CONTROL) instead.
isCtrl @ foundry.js:1726
Canvas._onDragLeftStart @ main.js:51
callback @ foundry.js:23985
_handleDragStart @ foundry.js:24302
_handleMouseMove @ foundry.js:24284
a.emit @ index.js:202
r.dispatchEvent @ interaction.min.js:8
r.processPointerMove @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerMove @ interaction.min.js:8

**Comment by CarlosFdez** [comment]
It wasn't intended to support click-drag but nice catch. I'll need to look into it to see what's going on with that error.

**Comment by CarlosFdez** [comment]
Can't reproduce. Might have been something else. Or its a 5e problem. Doesn't happen in pf2e.

**Comment by epsilon7430** [comment]
No longer seems to be an issue using FVTT 9.245 and DnD5e 1.5.7
