### ISSUE TITLE
Re-enabling the module to work for a scene forgets overlay image

### ISSUE THREAD

**Issue by epsilon7430** [CarlosFdez/world-explorer#15]
If an overlay image is set for the scene, disabling the module to work for the scene and then re-enabling it causes the overlay to default to the color instead of the image.

Thankfully, this issue can be worked around by selecting a different overlay image - saving changes - and then re-selecting the original overlay image - saving changes again.

**Comment by CarlosFdez** [comment]
Good catch. Actually its a lot worse than that. Any initial enabling fails, both in drawing the mask and setting an image. Will get it fixed by next release.

**Comment by CarlosFdez** [comment]
This should work now in 0.5.0.

**Comment by epsilon7430** [comment]
Confirming that it does work now.  Thanks!
