### ISSUE TITLE
0.5.0 incompatible with Enhanced Terrain Module

### ISSUE THREAD

**Issue by epsilon7430** [CarlosFdez/world-explorer#16]
With Enhanced Terrain module active, the three fog tools work, however, they throw the two console errors for every use.  Note: there is no enhanced terrain regions on the scene in question.

Foundry VTT | **Error thrown in hooked function** '' for hook 'updateScene'
_call @ foundry.js:297
callAll @ foundry.js:253
callback @ foundry.js:10273
(anonymous) @ foundry.js:10212
_handleUpdateDocuments @ foundry.js:10212
_updateDocuments @ foundry.js:10093
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
setFlag @ document.mjs:604
reveal @ world-explorer-layer.mjs:216
(anonymous) @ world-explorer-layer.mjs:269
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.js:8
r.processPointerDown @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerDown @ interaction.min.js:8
foundry.js:316 
        
TypeError: Cannot read properties of undefined (reading 'render')
[Detected 1 package: enhanced-terrain-layer]
    at terrain-main.js:463:25
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10273:13)
    at foundry.js:10212:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10212:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:10093:17)
    at async Function.updateDocuments (document.mjs:373:21)
    at async Scene.update (document.mjs:456:21)

**Comment by CarlosFdez** [comment]
It seems this is actually a bug on Monk's end. They are not checking for the existence of their toolbar. Apparently he will be notified and I owe someone my firstborn child for this favor I have received.

**Comment by epsilon7430** [comment]
Thanks for the update.  Sounds like a good "play well together" improvement to the ETL module.

**Comment by CarlosFdez** [comment]
I believe this is fixed now and has been for a while now. Please close if it is.

**Comment by epsilon7430** [comment]
Appears fixed.  Thanks for coordinating that!
