### ISSUE TITLE
Feature Request: Better GM view controls

### ISSUE THREAD

**Issue by lordyod** [CarlosFdez/world-explorer#18]
It would be great if the GM had some UI controls. Two controls I find that I wish I had are a hide/reveal button and a slider for the fog opacity.

A hide/reveal button could work just as the show/hide pin button for journal entries, making it so the fog is either visible or not when any set of tools other than the world explorer is selected.

A fog opacity slider could work just as the existing control in the scene configuration menu, just without needing to reload the scene.

**Comment by CarlosFdez** [comment]
I do like the idea of a slider for fog opacity.

That said, what do you mean by show/hide? You mean make the "fog" disappear entirely so the GM can fully see under it momentarily?

**Comment by lordyod** [comment]
> That said, what do you mean by show/hide? You mean make the "fog" disappear entirely so the GM can fully see under it momentarily?

The basic idea is, if I'm in the World Explorer toolbar I want to see the fog layer (at whatever opacity I have it set to), but if I'm on another layer I might not want it at all. This button would make it behave like journal pins, i.e. if you have the button enabled then you see the overlay while in other layers (token, tile, whatever) but if you have it disabled then you only see the 'fog' layer if you are on the world explorer toolbar.

**Comment by CarlosFdez** [comment]
I added the opacity slider in the latest release (lmk if there are problems) but as for that button, that sort of workflow sounds awkward usability wise. That seems like it should be a global module setting to behave that way rather than an outright toggle, especially when an opacity slider exists. Is there another module or built in control that behaves in the way you're thinking somewhere else?

**Comment by lordyod** [comment]
This release works pretty well!

An example of the on/off behavior is the 'hide/reveal map pins' control in the journal section, or in the political map overlay module which has a similar button: https://github.com/cirrahn/foundry-polmap

**Comment by CarlosFdez** [comment]
Is a full on/off switch still something in demand for you? I figured the slider was enough for the use case, but it could maybe be possible to add a little checkbox to the current slider to fully turn it off for the GM? My concern right now (which applies to the slider) is that its not quite obvious that it only affects the GM.
