### ISSUE TITLE
Hexes aren't fully erased

### ISSUE THREAD

**Issue by snakch** [CarlosFdez/world-explorer#20]
Heya! There seems to be a bug where on some hexes, the overlay isn't fully erased, leaving a thing strip of about 1 pixel wide between some of the edges. My Grid size is 93 (weird number but I needed it to line up with the map), I think that's probably what's causing it.

Here is what I mean, before erasing:

![image](https://user-images.githubusercontent.com/44138312/172056789-b22dfe9e-90ef-491a-8164-354076c43153.png)

After:
![image](https://user-images.githubusercontent.com/44138312/172056724-e6681a47-bec0-4790-81d0-2e73a75f4022.png)

**Comment by CarlosFdez** [comment]
This is on 0.6.1?

**Comment by snakch** [comment]
It is indeed on 0.6.1. 

I'll attach the assets + a screenshot of my grid configuration. This happens pretty much everywhere, just start uncovering random large portions of the map and you should see it

(I'm guessing this is due to some annoying integer division stuff that occurs when you use weird grid dimensions like me)

![crash_landed_bare](https://user-images.githubusercontent.com/44138312/176855007-69cfd38d-5d41-4088-bc51-e42dd7f330df.png)
![crash_landed_no_labels](https://user-images.githubusercontent.com/44138312/176855017-fc249a59-f5d1-478e-9577-8b171ac0b89b.png)
![Screenshot 2022-07-01 at 09 16 39](https://user-images.githubusercontent.com/44138312/176855082-fba51de5-3b68-40dc-86fb-675ec857c242.png)

**Comment by CarlosFdez** [comment]
Thanks. I have no clue why I don't have any notifications, but after monday I can start checking this.

**Comment by CarlosFdez** [comment]
Should be fixed in version 0.6.2. If it works I can close the issue.

Its not just that you used an odd configuration, but the workaround I did only worked for hexagonal rows. I had to do something extra for hexagonal columns to patch the seams as well.

**Comment by snakch** [comment]
It works on my end, thanks for fixing it!

**Comment by CarlosFdez** [comment]
No problem! Glad to hear its working now.
