### ISSUE TITLE
Fails to install on V10 with error

### ISSUE THREAD

**Issue by farling42** [CarlosFdez/world-explorer#21]
![image](https://user-images.githubusercontent.com/17485384/186884444-2f236e8c-d72d-4d50-8d38-e15379052599.png)

**Comment by arirawr** [comment]
+1, same issue here :)

**Comment by CarlosFdez** [comment]
Thanks for reporting. As of testing 5 they became more restricted on the manifest, so I'll need to tweak that real quick.

**Comment by CarlosFdez** [comment]
Should be resolved now
