### ISSUE TITLE
"Installation failed: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by wickermoon** [CarlosFdez/world-explorer#22]
Hi, I tried updating World explorer. A normal update just gave me "undefined" for version 0.7.2, so I wanted to un- and reinstall it, but when trying to reinstall it, I got the title's error message. ATM it's impossible to install this module. :/

**Comment by CarlosFdez** [comment]
comment if still broken, but I recall you posting in the discord and it being resolved!
