### ISSUE TITLE
not working under v10 

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [CarlosFdez/world-explorer#23]
On v10 the module does not work. The button does not appear in the control sidebar. 
I created a new world to test out if this is a migration issue, but nope - doesn't work on a fresh world either.

**Comment by CarlosFdez** [comment]
I did an uninstall and reinstall and it works fine. I'm suspecting its either a module conflict (maybe perfect vision), or you forgot to enable it for the current scene.
