### ISSUE TITLE
Map overlay not properly alligned

### ISSUE THREAD

**Issue by KJTailor** [CarlosFdez/world-explorer#26]
Yesterday I noticed a glaring error with the game for the first time. The overworld "world explorer" layer as well as the hex grid are not aligned with the map properly (see image attached)

![image](https://user-images.githubusercontent.com/87787745/202969416-19a46777-af28-4474-a9e0-3b2a6e68f941.png)

I'm in the process trying to figure out whether that is a particular module causing this, but given it happens only on the one map that 
- a) has hex grid enabled
and b) world explorer enabled and working on it
I thought I'll ask here first, if you have any idea what that could be?

Cheers

**Comment by KJTailor** [comment]
What I found out by now, it is a v10 foundry issue with hex maps. Investigating, I found out it ís still happening wíth ALL MODS TURNED OFF.

But I also learned that it only happens when the grid opacity is zero. As soon as the grid opacity is above 0, even 0.05, the issue consistently disappears, and world explorer functions as normal as well, for me AND the players.

Íts only a workaround, but at least it helps

**Comment by Threvlin** [comment]
Turning up the opacity to 0.05 does appear to have resolved the issue for now. Thankfully the map I'm using works fine with a light in-game grid being present. Thank you so much for the work around!

**Comment by CarlosFdez** [comment]
Is this still an issue? I found an issue just today where it happens if you reveal a grid hex that is partially offscreen.

**Comment by KJTailor** [comment]
After finding the 'fix' by changing the grid opacity, I never had an issue with it again. Sorry I can't help any further
