### ISSUE TITLE
Feature Request: Add a "reveal all tiles" button

### ISSUE THREAD

**Issue by nschoenwald** [CarlosFdez/world-explorer#28]
I have a map that will be mostly revealed to the players from the start, but there is an area that is hidden. It would save me a lot of work if I could set the whole map to revealed and then only hide the tiles for the unknown area.

**Comment by CarlosFdez** [comment]
Saw this late, but this isn't a bad idea. Just need to find a good way to present this, ideally something better than a show all or hide all button.

**Comment by CarlosFdez** [comment]
Its 2 months later but I finally implemented it as a scene reset option:
![image](https://github.com/CarlosFdez/world-explorer/assets/1286721/fed03160-b17e-4fec-9100-b0b1665b60ab)

There's a small bug involving the offscreen row that I don't really know how to fix. This row cannot be manually unset (I cannot seem to highlight it at all, and grid calculations involving them get weird), so I don't feel comfortable creating a discrepancy for reset all. That said, its a minor bug.
![image](https://github.com/CarlosFdez/world-explorer/assets/1286721/53e164a6-5276-4bbc-9376-0635a457dd16)

Hopefully this is more or less what you wanted though, even if its probably late for your game currently.

**Comment by nschoenwald** [comment]
It's too late for my current group, but will be super useful when I run my next group through the jungles of chult! Thank you! :)
