### ISSUE TITLE
World Explorer currently not functioning on v11

### ISSUE THREAD

**Issue by Slothman1** [CarlosFdez/world-explorer#29]
I'm unsure if this is an isolated incident on my game however the module appears to be broken and not functioning, the map overlay and individual revealing of hexes aren't working.

**Comment by Schnorks23** [comment]
Nope, not isolated. Same here. Seems broken since updating FoundryVTT on v11.

**Comment by erikhuck** [comment]
Yeah it doesn't seem to be working at all for me. The map is not hidden for players so revealing / hiding hexes does nothing.
