### ISSUE TITLE
Map crash

### ISSUE THREAD

**Issue by mrlnfiniti** [CarlosFdez/world-explorer#32]
Hello, I don't know if this is your mod interacting weirdly with another mod or otherwise, but If I try to change the status of the world fog map (hiding or revealing the tiles), the map crashes really hard, doesn't matter if I go fast or hard, it always crashes at one point. I'll post the error and a video for your to see.
![Problema Foundry](https://github.com/CarlosFdez/world-explorer/assets/135876436/ca1114b4-564f-4909-a1b5-2f2bea414973)
![Problema Foundry 2](https://github.com/CarlosFdez/world-explorer/assets/135876436/f50af105-8ebc-4a5d-b133-18aa6e4db71e)

https://github.com/CarlosFdez/world-explorer/assets/135876436/2bddf97d-08bd-4e4b-b919-efd7d1d36ed0

**Comment by CarlosFdez** [comment]
I'm going to need a bit more info, I cannot reproduce

https://github.com/CarlosFdez/world-explorer/assets/1286721/34c93310-5e21-46f2-b368-d9c8ab8106c6

That warning you're seeing in the console isn't happening either, are you on 0.8.2?

**Comment by mrlnfiniti** [comment]
I am. It happens when I reveal tiles quickly, also I have the keep the zone revealed after the token leaving on

**Comment by CarlosFdez** [comment]
What I'm seeing that's different is that for me it only reveals at the start and end, and for you its revealing every step of the way. Does this continue without any other modules? And if so, what system? If no, what other module seems to cause this?

**Comment by mrlnfiniti** [comment]
Mod: Only yours
System: pathfinder 2e 4.12.9
It's revealing every step because I'm making waypoints in every tile. Look CTRL drag controls for that
Here is another vid for your to see, still happening. Also It doesn't seem to support Images bigger than 11k pixels

https://github.com/CarlosFdez/world-explorer/assets/135876436/791e8fe4-df25-4b07-bfa2-2582bdf879c9

**Comment by CarlosFdez** [comment]
I see. I received a PR for V11 and support, but the min was still set to V10 so I assumed it still supported V10. I'll see if that's the issue and come up with a fix if so.

I didn't realize you were still on v10 until you mentioned pathfinder 2e.

**Comment by mrlnfiniti** [comment]
Thanks man, I really like your mod, good luck for looking for the issue!

**Comment by CarlosFdez** [comment]
Feel free to message me on discord regarding this. I'm one of the code leads on the pathfinder 2e server so I should be very easy to find.

**Comment by CarlosFdez** [comment]
After some digging, it turned out to be a memory leak that is apparent on larger maps. I will attempt to fix it really soon.

**Comment by CarlosFdez** [comment]
0.8.3 is an attempt to fix it. Let me know if it continues.

**Comment by CarlosFdez** [comment]
It seems it didn't, but it seems like 0.8.4 did fix it! I will close, but feel free to reopen if its still broken.
