### ISSUE TITLE
PF2E Flanking Detection Not Working with World Explorer Loaded

### ISSUE THREAD

**Issue by Cosmic-Lattee** [CarlosFdez/world-explorer#38]
So strange thing happened tonight. I accidently turned on world explorer for one of my games when I was enabling other modules and I noticed that off-guard wasn't automatically applying.

I went through find the culprit and World Explorer is what was causing the issue. I wasn't even using the module or anything on the map it was just loaded. Once I turned it off flanking detection started working again. 

 Tested with 5.3.0 PF2E and Foundry 11 build 306

**Comment by CarlosFdez** [comment]
I actually cannot reproduce this. Not only should this not be possible (unless there are errors, check if there's errors by world explorer), I tested with it enabled and disabled for a square grid scene and flanking is working fine.

**Comment by Cosmic-Lattee** [comment]
Huh interesting. Not sure what would be causing it with just World Explorer open then. 

Guess something else is going on then. 

Thanks!

**Comment by CarlosFdez** [comment]
The only thing I can imagine is that you're running an older version, which did have some crashes in v11. These crashes may prevent other things from occurring.

**Comment by Cosmic-Lattee** [comment]
Yeah not sure. I ended up uninstalling foundry and reinstalling it and it works now? Might have been a update or something. Idk but it seems to be working now. XD

**Comment by CarlosFdez** [comment]
This is so weird. Interesting!
