### ISSUE TITLE
I am getting multiple errors relating to different modules when I click on the world explorer icon (screenshot provided)

### ISSUE THREAD

**Issue by YenBenGrey** [CarlosFdez/world-explorer#39]
Hello, 

Before I explain the issue, I want to say how utterly amazing this module is!

Anyway I am using Foundry via The Forge with the following versions of a game - 
Foundry 11.309
DND5e 2.3.1
World Explorer 0.8.4

I have a screenshot....

![Screenshot 2023-09-26 at 22 22 41](https://github.com/CarlosFdez/world-explorer/assets/98095856/26446cb4-f0d3-4b4a-a9d6-0953aea69ecc)

**Comment by CarlosFdez** [comment]
Thanks!

That said, I'm not getting those errors personally. Given the inclusion of tactical-grid.js, might it be a module confliction?

**Comment by YenBenGrey** [comment]
Hello Carlos, 

Since having this issue, and many many many others not relating to World Explorer, I have left The Forge and now with a different hosting service. 

I now do not have any of these problems. :-)

**Comment by CarlosFdez** [comment]
I'll need to at a later date see if world explorer has a forge bug.

Out of curiosity, since I know some people who use Forge, what hosting service do you use now?

**Comment by YenBenGrey** [comment]
I’m using Molten now. 
However today I got the same errors but they didn’t seem to cause any actual problem on the canvas. 
They appeared whenever I clicked on the World Explorer icon on the left. But then I could use everything as normal. 
Might be a module clash. Like you said.
