### ISSUE TITLE
Hiding drawings/text?

### ISSUE THREAD

**Issue by ericvoshall** [CarlosFdez/world-explorer#40]
Is there a way to keep drawings and text on a tile hidden until that tile is revealed? Drawings and text are currently displayed on top of the overlay.

**Comment by CarlosFdez** [comment]
This can be controlled via the z index on either the tile, or in the settings.

**Comment by CarlosFdez** [comment]
I added a new relative position setting (replacing zIndex) in world explorer version 0.9.0 which should hopefully handle most of the ~~weird~~ use cases people have.

![image](https://github.com/CarlosFdez/world-explorer/assets/1286721/bebfb459-5b84-49e5-8855-fa4571e612f8)

Feel free to reopen if it doesn't solve your issue.
