### ISSUE TITLE
Map update for players/GM

### ISSUE THREAD

**Issue by aziles-guts** [CarlosFdez/world-explorer#43]
I'm not exactly sure why or if it is working as intended, but I have a token on my Map Scene that is meant to give visibility to the hex it is in however it doesn't seem to update the visible area when the token moves for my players.

**Comment by CarlosFdez** [comment]
That's a setting. By default its meant for manual reveals such as via reconnoiter.

**Comment by 13jtibbitts** [comment]
I'm having the same issue. What setting is supposed to be changed to dynamically update the view when the token moves?

**Comment by aziles-guts** [comment]
I think the problem is that

**Comment by aziles-guts** [comment]
Sorry for closing it, the problem is something to do with how it updates back to the players. The map view on the GM's view does update with the token moving while the token exploration is active (I believe in the scene settings?) my problem is that my players do not see the map changes reflected as I do while I move the token around unless i reveal and unreveal a portion of the map to force it to update.
