### ISSUE TITLE
Feature Request: Reset Fog of war | explored tiles

### ISSUE THREAD

**Issue by Freezor** [CarlosFdez/world-explorer#44]
I struggled a bit to make it work, so I tested a bit of movement and did not find a way to reset the fog of war.
Maybe, if possible, a way to reset explored tiles would be nice.

**Comment by CarlosFdez** [comment]
This should be the trash icon in the world explorer canvas controls

**Comment by Freezor** [comment]
Ah. that's what that does 😄 Now I got it. Thanks
