### ISSUE TITLE
Vision for Party Actor

### ISSUE THREAD

**Issue by Freezor** [CarlosFdez/world-explorer#45]
Maybe a feature request or a bug, but I wasn't able to get tiles revealed when using a party-type actor.

**Comment by Freezor** [comment]
Hi. Yes that still persists at least in DnD5e version 2.4.0

**Comment by Freezor** [comment]
Hmm... I don't know what exactly fixed at now. But apparently readding the actor might have fixed it. I had the party actor on the map before activating World-Explorer. As you said that it should normally work, I added the actor again and now it works. 
Maybe there is some bug with the initialisation, but re-adding the party actor on the map is a good workaround. 
Thanks for your help ❤️

**Comment by CarlosFdez** [comment]
Might have been a token disposition misconfiguration. Those are I think changed in the token config. World Explorer only reveals when a token has the friendly disposition.
