### ISSUE TITLE
bug revealed hexes

### ISSUE THREAD

**Issue by tirzah2** [CarlosFdez/world-explorer#46]
Hi!
I don't know why but every week i need to open the main hexploration map and start hiding hexes by hand because always, in the top left corner, they auto reveal themselves. I dont know why, but its always in the top left corner of the map and always randomly. 
![image](https://github.com/CarlosFdez/world-explorer/assets/83312683/83a5f36b-4e98-47ea-ab65-a5e5d347dbaf)

**Comment by Xelveki** [comment]
I am also having an issue where small smatterings of tiles are revealed regularly without any reason I can identify.

**Comment by CarlosFdez** [comment]
Are there any errors in the console? Also is this v12? If tiles are not properly unrevealing, there may be an error with the update specifically.

**Comment by CarlosFdez** [comment]
I noticed there was a bug with the update throttling, so it might helpful to test again in the v12 version once you can finally update.

**Comment by Xelveki** [comment]
I'm still on v11. I've got 11 warnings about stability for other mods, one about an error thrown in a hooked function, and a TypeError thrown from the hooked function about Cannot read properties of undefined (reading 'ColorSetting'),

**Comment by Xelveki** [comment]
Been a bit. We're on Foundry v12.330 and v1.0 of world-explorer. Our worldmap is a hex map and we're still periodically seeing revealed tiles. Sometimes individually and sometimes in lines or chunks. I'd love to know what's causing it or if there's anything I can do to fix it. 

Let me know what information you might need.

**Comment by morepurplemorebetter** [comment]
I have an idea what might be causing this. When you have the hide/reveal tool active and drag a dialog or an item from the sidebar (or even hold your mouse button down while within a dialog), the hide/reveal action still gets performed behind the dialog, making it seem it happened by a ghost.

I have a (partial) fix for this issue in PR #49.

**Comment by CarlosFdez** [comment]
That seems to 100% be it. Nice call. I looked at the PR and I got the fix inspired from there, though I did my own take on it. This should hopefully stop happening once the next patch release is out.

**Comment by morepurplemorebetter** [comment]
I'm happy to have helped and that this is now resolved. I wasn't sure what the best way to fix it was, so I went with the least amount of changes.
